# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_worker" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    manager: ${aws_instance.swarm-manager.public_ip}

    DOC
  filename = "../ansible/roles/swarm-worker/vars/main.yaml"
}