# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    swarm-manager: ${aws_instance.swarm-manager.public_ip}
    swarm-worker: ${aws_instance.swarm-worker.public_ip}
    nginx-lb: ${aws_instance.nginx.public_ip}
    DOC
  filename = "./tf_ansible_vars_file.yml"
}