all:
  children:
    manager:
      hosts:
        3.8.89.70:
    worker:
      hosts:
        18.134.161.3:
    nginx-lb:
      hosts:
        13.40.113.81:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/aws-key-london.pem'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'