---
# tasks file for swarm-manager

- name: Initialise swarm on manager
  docker_swarm:
    state: present

- name: get token info
  docker_swarm_info:
  register: swarm_info

- name: output info
  debug:
    msg: "{{ swarm_info }}"

